### ISSUE TITLE
Intermittent failures with javascript_pack_tag on CI

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#324]
We're seeing [occasional build failures](https://app.circleci.com/pipelines/github/rubyforgood/circulate/559/workflows/22e2e884-4306-44ce-bfb9-da08066c032a/jobs/2945) on CircleCI that look like this:

```
783: unexpected token at ''
app/views/layouts/application.html.erb:12
app/controllers/member_profiles_controller.rb:15:in `block (2 levels) in update'
app/controllers/member_profiles_controller.rb:10:in `update'
app/controllers/application_controller.rb:27:in `block in set_time_zone'
app/controllers/application_controller.rb:25:in `set_time_zone'
test/controllers/member_profiles_controller_test.rb:29:in `block in <class:MemberProfilesControllerTest>'
```

These are always resolved by re-running the failed test. They seem to stem from the JavaScript tooling somewhere since the error is happening in the `javascript_pack_tag` call on line 12 of `application.html.erb`.

Another clue I've noticed is that the `test` jobs that fail take longer to run (~1m 20s) than the ones that pass (~60s), so perhaps there is something timing out somewhere. Perhaps we need to explicitly build the assets in the CI script before running tests?

**Comment by raulpopadineti** [comment]
Same here 🖐🏻

**Comment by jim** [comment]
@raulpopadineti I haven't figured this out yet. I've been planning to migrate CI to use the same Docker setup that we have for development in the hopes that it would be easier to troubleshoot the problem, but we haven't gotten to that yet.
