### ISSUE TITLE
System tests can't run in Docker on Mac

### ISSUE THREAD

**Issue by jim** [rubyforgood/circulate#660]
**Describe the bug**

Running `rails test:system` doesn't work in Docker (at least on a Mac) as mentioned [in this PR](https://github.com/rubyforgood/circulate/pull/659#issuecomment-920461684):

```
Error:
Admin::AppointmentsTest#test_marks_an_appointment_as_completed:
ArgumentError: unknown driver: :headless_chrome_in_container
    /usr/local/bundle/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver/common/driver.rb:60:in `for'
    /usr/local/bundle/gems/selenium-webdriver-3.142.7/lib/selenium/webdriver.rb:88:in `for'
    /usr/local/bundle/gems/capybara-3.35.3/lib/capybara/selenium/driver.rb:83:in `browser'
    /usr/local/bundle/gems/actionpack-6.1.3.2/lib/action_dispatch/system_testing/driver.rb:48:in `block in register_selenium'
    /usr/local/bundle/gems/actionpack-6.1.3.2/lib/action_dispatch/system_testing/driver.rb:47:in `tap'
    /usr/local/bundle/gems/actionpack-6.1.3.2/lib/action_dispatch/system_testing/driver.rb:47:in `register_selenium'
    /usr/local/bundle/gems/actionpack-6.1.3.2/lib/action_dispatch/system_testing/driver.rb:35:in `block in register'
    /usr/local/bundle/gems/capybara-3.35.3/lib/capybara/session.rb:104:in `driver'
    /usr/local/bundle/gems/capybara-3.35.3/lib/capybara/session.rb:90:in `initialize'
    /usr/local/bundle/gems/capybara-3.35.3/lib/capybara.rb:424:in `new'
    /usr/local/bundle/gems/capybara-3.35.3/lib/capybara.rb:424:in `block in session_pool'
    /usr/local/bundle/gems/capybara-3.35.3/lib/capybara.rb:315:in `current_session'
    /usr/local/bundle/gems/capybara-3.35.3/lib/capybara/dsl.rb:46:in `page'
    /usr/local/bundle/gems/actionpack-6.1.3.2/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:95:in `save_image'
    /usr/local/bundle/gems/actionpack-6.1.3.2/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:33:in `take_screenshot'
    /usr/local/bundle/gems/actionpack-6.1.3.2/lib/action_dispatch/system_testing/test_helpers/screenshot_helper.rb:45:in `take_failed_screenshot'
    /usr/local/bundle/gems/actionpack-6.1.3.2/lib/action_dispatch/system_testing/test_helpers/setup_and_teardown.rb:16:in `before_teardown'
```

**Expected behavior**

The system tests should run without issues when a developer is using Docker to run the app.

**Comment by jim** [comment]
Fixed by #679
